AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CoAutoBackend

  Sample SAM Template for CoAuto_Backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UserApi
      StageName: Prod
  CarApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: CarApi
      StageName: Prod

  GetDataUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetDataUser:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /get_data
            Method: get

  InsertDataUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: insert_data_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetDataStudent:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /insert_data
            Method: post

  UpdateDataUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_data_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetDataStudent:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /update_data
            Method: put

  DeleteDataUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_data_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetDataStudent:
          Type: Api
          Properties:
            RestApiId: !Ref UserApi
            Path: /delete_data
            Method: delete

  GetDataCarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data_car/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetDataUser:
          Type: Api
          Properties:
            RestApiId: !Ref CarApi
            Path: /get_data
            Method: get

Outputs:
  GetDataUserApiUrl:
    Description: "API Gateway endpoint URL with path get_data for Prod stage to User Model"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_data"
  InsertDataUserApiUrl:
    Description: "API Gateway endpoint URL with path insert_data for Prod stage to User Model"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/insert_data"
  UpdateDataUserApiUrl:
    Description: "API Gateway endpoint URL with path update_data for Prod stage to User Model"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_data"
  DeleteDataUserApiUrl:
    Description: "API Gateway endpoint URL with path delete_data for Prod stage to User Model"
    Value: !Sub "https://${UserApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_data"
  GetDataUserFunctionArn:
    Description: "Get data user Lambda Function ARN"
    Value: !GetAtt GetDataUserFunction.Arn
  InsertDataUserFunctionArn:
    Description: "Insert data user Lambda Function ARN"
    Value: !GetAtt InsertDataUserFunction.Arn
  UpdateDataUserFunctionArn:
    Description: "Update data user Lambda Function ARN"
    Value: !GetAtt UpdateDataUserFunction.Arn
  DeleteDataUserFunctionArn:
    Description: "Delete data user Lambda Function ARN"
    Value: !GetAtt DeleteDataUserFunction.Arn

    GetDataCarApiUrl:
      Description: "API Gateway endpoint URL with path get_data for Prod stage to Car Model"
      Value: !Sub "https://${CarApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_data"
    GetDataUserFunctionArn:
      Description: "Get data car Lambda Function ARN"
      Value: !GetAtt GetDataCarFunction.Arn

  LambdaExecutionRoleArn:
    Description: "Lambda Execution Role ARN"
    Value: !GetAtt LambdaExecutionRole.Arn