name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies for user service
        run: |
          pip install -r user/get_data_user/requirements.txt
          pip install -r user/insert_data_user/requirements.txt
          pip install -r user/update_data_user/requirements.txt
          pip install -r user/delete_data_user/requirements.txt

      - name: Install dependencies for car service
        run: |
          pip install -r car/get_data_car/requirements.txt
          pip install -r car/insert_data_car/requirements.txt
          pip install -r car/update_data_car/requirements.txt
          pip install -r car/delete_data_car/requirements.txt

      - name: Install dependencies for rate service
        run: |
          pip install -r rate/get_data_rate/requirements.txt
          pip install -r rate/insert_data_rate/requirements.txt
          pip install -r rate/get_one_data_rate/requirements.txt

      - name: Install dependencies for cognito service
        run: |
          pip install -r cognito/sign_up/requirements.txt
          pip install -r cognito/resend_confirmation_code/requirements.txt
          pip install -r cognito/confirm_sign_up/requirements.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_lambda:
    name: Deploy Lambda to AWS
    runs-on: ubuntu-latest
    needs: sonarcloud
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies for user service
        run: |
          pip install -r user/requirements.txt
          pip install -r user/insert_data_user/requirements.txt
          pip install -r user/update_data_user/requirements.txt
          pip install -r user/delete_data_user/requirements.txt

      - name: Install dependencies for car service
        run: |
          pip install -r car/get_data_car/requirements.txt
          pip install -r car/insert_data_car/requirements.txt
          pip install -r car/update_data_car/requirements.txt
          pip install -r car/delete_data_car/requirements.txt

      - name: Install dependencies for rate service
        run: |
          pip install -r rate/get_data_rate/requirements.txt
          pip install -r rate/get_one_data_rate/requirements.txt
          pip install -r rate/insert_data_rate/requirements.txt

      - name: Install dependencies for cognito service
        run: |
          pip install -r cognito/sign_up/requirements.txt
          pip install -r cognito/resend_confirmation_code/requirements.txt
          pip install -r cognito/confirm_sign_up/requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli
      - name: Build SAM application
        run: sam build
      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name CoAutoBackend --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1